# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c55e932a0fd0961b022ebcdfc71848f6e9300c765e3eae76c5524f6b58626455f7fc275c106a4698ab5c01a7cfad1d2b6a274ab9bd2d38664cf1802f2ed50af2

test:
  secret_key_base: 975f24c3a7e8a22eb41a5a9bb97dac1c803845a1742573d4c443c9f0081830cf72460d349dbe9e7929f4ab137d9945894c70c3bedb5d3a56ed0038550825fb87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
